// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TaxiTrip.proto
package utilities;

public final class TaxiTripOuterClass {
  private TaxiTripOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaxiTripOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TaxiTrip)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string TaxiCompany = 1;</code>
     * @return The taxiCompany.
     */
    java.lang.String getTaxiCompany();
    /**
     * <code>string TaxiCompany = 1;</code>
     * @return The bytes for taxiCompany.
     */
    com.google.protobuf.ByteString
        getTaxiCompanyBytes();

    /**
     * <code>int64 Vendor_Id = 2;</code>
     * @return The vendorId.
     */
    long getVendorId();

    /**
     * <code>string Pickup_DateTime = 3;</code>
     * @return The pickupDateTime.
     */
    java.lang.String getPickupDateTime();
    /**
     * <code>string Pickup_DateTime = 3;</code>
     * @return The bytes for pickupDateTime.
     */
    com.google.protobuf.ByteString
        getPickupDateTimeBytes();

    /**
     * <code>string Dropoff_DateTime = 4;</code>
     * @return The dropoffDateTime.
     */
    java.lang.String getDropoffDateTime();
    /**
     * <code>string Dropoff_DateTime = 4;</code>
     * @return The bytes for dropoffDateTime.
     */
    com.google.protobuf.ByteString
        getDropoffDateTimeBytes();

    /**
     * <code>string Store_And_Forward = 5;</code>
     * @return The storeAndForward.
     */
    java.lang.String getStoreAndForward();
    /**
     * <code>string Store_And_Forward = 5;</code>
     * @return The bytes for storeAndForward.
     */
    com.google.protobuf.ByteString
        getStoreAndForwardBytes();

    /**
     * <code>int64 Rate_Code_Id = 6;</code>
     * @return The rateCodeId.
     */
    long getRateCodeId();

    /**
     * <code>int64 PULocationID = 7;</code>
     * @return The pULocationID.
     */
    long getPULocationID();

    /**
     * <code>int64 DOLocationID = 8;</code>
     * @return The dOLocationID.
     */
    long getDOLocationID();

    /**
     * <code>int64 Passenger_Count = 9;</code>
     * @return The passengerCount.
     */
    long getPassengerCount();

    /**
     * <code>double Trip_Distance = 10;</code>
     * @return The tripDistance.
     */
    double getTripDistance();

    /**
     * <code>double Fare_Amount = 11;</code>
     * @return The fareAmount.
     */
    double getFareAmount();

    /**
     * <code>double Surcharge = 12;</code>
     * @return The surcharge.
     */
    double getSurcharge();

    /**
     * <code>double MTA_Tax = 13;</code>
     * @return The mTATax.
     */
    double getMTATax();

    /**
     * <code>double Tip_Amount = 14;</code>
     * @return The tipAmount.
     */
    double getTipAmount();

    /**
     * <code>double Tolls_Amount = 15;</code>
     * @return The tollsAmount.
     */
    double getTollsAmount();

    /**
     * <code>double Improvement_Surcharge = 16;</code>
     * @return The improvementSurcharge.
     */
    double getImprovementSurcharge();

    /**
     * <code>double Total_Amount = 17;</code>
     * @return The totalAmount.
     */
    double getTotalAmount();

    /**
     * <code>int64 Payment_Type_Id = 18;</code>
     * @return The paymentTypeId.
     */
    long getPaymentTypeId();

    /**
     * <code>double Congestion_Surcharge = 19;</code>
     * @return The congestionSurcharge.
     */
    double getCongestionSurcharge();

    /**
     * <code>int64 Trip_Type = 20;</code>
     * @return The tripType.
     */
    long getTripType();

    /**
     * <code>double Ehail_Fee = 21;</code>
     * @return The ehailFee.
     */
    double getEhailFee();

    /**
     * <code>string PartitionDate = 22;</code>
     * @return The partitionDate.
     */
    java.lang.String getPartitionDate();
    /**
     * <code>string PartitionDate = 22;</code>
     * @return The bytes for partitionDate.
     */
    com.google.protobuf.ByteString
        getPartitionDateBytes();
  }
  /**
   * Protobuf type {@code TaxiTrip}
   */
  public static final class TaxiTrip extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TaxiTrip)
      TaxiTripOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaxiTrip.newBuilder() to construct.
    private TaxiTrip(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaxiTrip() {
      taxiCompany_ = "";
      pickupDateTime_ = "";
      dropoffDateTime_ = "";
      storeAndForward_ = "";
      partitionDate_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaxiTrip();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaxiTrip(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              taxiCompany_ = s;
              break;
            }
            case 16: {

              vendorId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              pickupDateTime_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              dropoffDateTime_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              storeAndForward_ = s;
              break;
            }
            case 48: {

              rateCodeId_ = input.readInt64();
              break;
            }
            case 56: {

              pULocationID_ = input.readInt64();
              break;
            }
            case 64: {

              dOLocationID_ = input.readInt64();
              break;
            }
            case 72: {

              passengerCount_ = input.readInt64();
              break;
            }
            case 81: {

              tripDistance_ = input.readDouble();
              break;
            }
            case 89: {

              fareAmount_ = input.readDouble();
              break;
            }
            case 97: {

              surcharge_ = input.readDouble();
              break;
            }
            case 105: {

              mTATax_ = input.readDouble();
              break;
            }
            case 113: {

              tipAmount_ = input.readDouble();
              break;
            }
            case 121: {

              tollsAmount_ = input.readDouble();
              break;
            }
            case 129: {

              improvementSurcharge_ = input.readDouble();
              break;
            }
            case 137: {

              totalAmount_ = input.readDouble();
              break;
            }
            case 144: {

              paymentTypeId_ = input.readInt64();
              break;
            }
            case 153: {

              congestionSurcharge_ = input.readDouble();
              break;
            }
            case 160: {

              tripType_ = input.readInt64();
              break;
            }
            case 169: {

              ehailFee_ = input.readDouble();
              break;
            }
            case 178: {
              java.lang.String s = input.readStringRequireUtf8();

              partitionDate_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TaxiTripOuterClass.internal_static_TaxiTrip_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TaxiTripOuterClass.internal_static_TaxiTrip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TaxiTripOuterClass.TaxiTrip.class, TaxiTripOuterClass.TaxiTrip.Builder.class);
    }

    public static final int TAXICOMPANY_FIELD_NUMBER = 1;
    private volatile java.lang.Object taxiCompany_;
    /**
     * <code>string TaxiCompany = 1;</code>
     * @return The taxiCompany.
     */
    @java.lang.Override
    public java.lang.String getTaxiCompany() {
      java.lang.Object ref = taxiCompany_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taxiCompany_ = s;
        return s;
      }
    }
    /**
     * <code>string TaxiCompany = 1;</code>
     * @return The bytes for taxiCompany.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaxiCompanyBytes() {
      java.lang.Object ref = taxiCompany_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taxiCompany_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VENDOR_ID_FIELD_NUMBER = 2;
    private long vendorId_;
    /**
     * <code>int64 Vendor_Id = 2;</code>
     * @return The vendorId.
     */
    @java.lang.Override
    public long getVendorId() {
      return vendorId_;
    }

    public static final int PICKUP_DATETIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object pickupDateTime_;
    /**
     * <code>string Pickup_DateTime = 3;</code>
     * @return The pickupDateTime.
     */
    @java.lang.Override
    public java.lang.String getPickupDateTime() {
      java.lang.Object ref = pickupDateTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pickupDateTime_ = s;
        return s;
      }
    }
    /**
     * <code>string Pickup_DateTime = 3;</code>
     * @return The bytes for pickupDateTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPickupDateTimeBytes() {
      java.lang.Object ref = pickupDateTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pickupDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DROPOFF_DATETIME_FIELD_NUMBER = 4;
    private volatile java.lang.Object dropoffDateTime_;
    /**
     * <code>string Dropoff_DateTime = 4;</code>
     * @return The dropoffDateTime.
     */
    @java.lang.Override
    public java.lang.String getDropoffDateTime() {
      java.lang.Object ref = dropoffDateTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dropoffDateTime_ = s;
        return s;
      }
    }
    /**
     * <code>string Dropoff_DateTime = 4;</code>
     * @return The bytes for dropoffDateTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDropoffDateTimeBytes() {
      java.lang.Object ref = dropoffDateTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dropoffDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STORE_AND_FORWARD_FIELD_NUMBER = 5;
    private volatile java.lang.Object storeAndForward_;
    /**
     * <code>string Store_And_Forward = 5;</code>
     * @return The storeAndForward.
     */
    @java.lang.Override
    public java.lang.String getStoreAndForward() {
      java.lang.Object ref = storeAndForward_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        storeAndForward_ = s;
        return s;
      }
    }
    /**
     * <code>string Store_And_Forward = 5;</code>
     * @return The bytes for storeAndForward.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStoreAndForwardBytes() {
      java.lang.Object ref = storeAndForward_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storeAndForward_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RATE_CODE_ID_FIELD_NUMBER = 6;
    private long rateCodeId_;
    /**
     * <code>int64 Rate_Code_Id = 6;</code>
     * @return The rateCodeId.
     */
    @java.lang.Override
    public long getRateCodeId() {
      return rateCodeId_;
    }

    public static final int PULOCATIONID_FIELD_NUMBER = 7;
    private long pULocationID_;
    /**
     * <code>int64 PULocationID = 7;</code>
     * @return The pULocationID.
     */
    @java.lang.Override
    public long getPULocationID() {
      return pULocationID_;
    }

    public static final int DOLOCATIONID_FIELD_NUMBER = 8;
    private long dOLocationID_;
    /**
     * <code>int64 DOLocationID = 8;</code>
     * @return The dOLocationID.
     */
    @java.lang.Override
    public long getDOLocationID() {
      return dOLocationID_;
    }

    public static final int PASSENGER_COUNT_FIELD_NUMBER = 9;
    private long passengerCount_;
    /**
     * <code>int64 Passenger_Count = 9;</code>
     * @return The passengerCount.
     */
    @java.lang.Override
    public long getPassengerCount() {
      return passengerCount_;
    }

    public static final int TRIP_DISTANCE_FIELD_NUMBER = 10;
    private double tripDistance_;
    /**
     * <code>double Trip_Distance = 10;</code>
     * @return The tripDistance.
     */
    @java.lang.Override
    public double getTripDistance() {
      return tripDistance_;
    }

    public static final int FARE_AMOUNT_FIELD_NUMBER = 11;
    private double fareAmount_;
    /**
     * <code>double Fare_Amount = 11;</code>
     * @return The fareAmount.
     */
    @java.lang.Override
    public double getFareAmount() {
      return fareAmount_;
    }

    public static final int SURCHARGE_FIELD_NUMBER = 12;
    private double surcharge_;
    /**
     * <code>double Surcharge = 12;</code>
     * @return The surcharge.
     */
    @java.lang.Override
    public double getSurcharge() {
      return surcharge_;
    }

    public static final int MTA_TAX_FIELD_NUMBER = 13;
    private double mTATax_;
    /**
     * <code>double MTA_Tax = 13;</code>
     * @return The mTATax.
     */
    @java.lang.Override
    public double getMTATax() {
      return mTATax_;
    }

    public static final int TIP_AMOUNT_FIELD_NUMBER = 14;
    private double tipAmount_;
    /**
     * <code>double Tip_Amount = 14;</code>
     * @return The tipAmount.
     */
    @java.lang.Override
    public double getTipAmount() {
      return tipAmount_;
    }

    public static final int TOLLS_AMOUNT_FIELD_NUMBER = 15;
    private double tollsAmount_;
    /**
     * <code>double Tolls_Amount = 15;</code>
     * @return The tollsAmount.
     */
    @java.lang.Override
    public double getTollsAmount() {
      return tollsAmount_;
    }

    public static final int IMPROVEMENT_SURCHARGE_FIELD_NUMBER = 16;
    private double improvementSurcharge_;
    /**
     * <code>double Improvement_Surcharge = 16;</code>
     * @return The improvementSurcharge.
     */
    @java.lang.Override
    public double getImprovementSurcharge() {
      return improvementSurcharge_;
    }

    public static final int TOTAL_AMOUNT_FIELD_NUMBER = 17;
    private double totalAmount_;
    /**
     * <code>double Total_Amount = 17;</code>
     * @return The totalAmount.
     */
    @java.lang.Override
    public double getTotalAmount() {
      return totalAmount_;
    }

    public static final int PAYMENT_TYPE_ID_FIELD_NUMBER = 18;
    private long paymentTypeId_;
    /**
     * <code>int64 Payment_Type_Id = 18;</code>
     * @return The paymentTypeId.
     */
    @java.lang.Override
    public long getPaymentTypeId() {
      return paymentTypeId_;
    }

    public static final int CONGESTION_SURCHARGE_FIELD_NUMBER = 19;
    private double congestionSurcharge_;
    /**
     * <code>double Congestion_Surcharge = 19;</code>
     * @return The congestionSurcharge.
     */
    @java.lang.Override
    public double getCongestionSurcharge() {
      return congestionSurcharge_;
    }

    public static final int TRIP_TYPE_FIELD_NUMBER = 20;
    private long tripType_;
    /**
     * <code>int64 Trip_Type = 20;</code>
     * @return The tripType.
     */
    @java.lang.Override
    public long getTripType() {
      return tripType_;
    }

    public static final int EHAIL_FEE_FIELD_NUMBER = 21;
    private double ehailFee_;
    /**
     * <code>double Ehail_Fee = 21;</code>
     * @return The ehailFee.
     */
    @java.lang.Override
    public double getEhailFee() {
      return ehailFee_;
    }

    public static final int PARTITIONDATE_FIELD_NUMBER = 22;
    private volatile java.lang.Object partitionDate_;
    /**
     * <code>string PartitionDate = 22;</code>
     * @return The partitionDate.
     */
    @java.lang.Override
    public java.lang.String getPartitionDate() {
      java.lang.Object ref = partitionDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partitionDate_ = s;
        return s;
      }
    }
    /**
     * <code>string PartitionDate = 22;</code>
     * @return The bytes for partitionDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPartitionDateBytes() {
      java.lang.Object ref = partitionDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partitionDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaxiCompanyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taxiCompany_);
      }
      if (vendorId_ != 0L) {
        output.writeInt64(2, vendorId_);
      }
      if (!getPickupDateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pickupDateTime_);
      }
      if (!getDropoffDateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dropoffDateTime_);
      }
      if (!getStoreAndForwardBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, storeAndForward_);
      }
      if (rateCodeId_ != 0L) {
        output.writeInt64(6, rateCodeId_);
      }
      if (pULocationID_ != 0L) {
        output.writeInt64(7, pULocationID_);
      }
      if (dOLocationID_ != 0L) {
        output.writeInt64(8, dOLocationID_);
      }
      if (passengerCount_ != 0L) {
        output.writeInt64(9, passengerCount_);
      }
      if (tripDistance_ != 0D) {
        output.writeDouble(10, tripDistance_);
      }
      if (fareAmount_ != 0D) {
        output.writeDouble(11, fareAmount_);
      }
      if (surcharge_ != 0D) {
        output.writeDouble(12, surcharge_);
      }
      if (mTATax_ != 0D) {
        output.writeDouble(13, mTATax_);
      }
      if (tipAmount_ != 0D) {
        output.writeDouble(14, tipAmount_);
      }
      if (tollsAmount_ != 0D) {
        output.writeDouble(15, tollsAmount_);
      }
      if (improvementSurcharge_ != 0D) {
        output.writeDouble(16, improvementSurcharge_);
      }
      if (totalAmount_ != 0D) {
        output.writeDouble(17, totalAmount_);
      }
      if (paymentTypeId_ != 0L) {
        output.writeInt64(18, paymentTypeId_);
      }
      if (congestionSurcharge_ != 0D) {
        output.writeDouble(19, congestionSurcharge_);
      }
      if (tripType_ != 0L) {
        output.writeInt64(20, tripType_);
      }
      if (ehailFee_ != 0D) {
        output.writeDouble(21, ehailFee_);
      }
      if (!getPartitionDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 22, partitionDate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaxiCompanyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taxiCompany_);
      }
      if (vendorId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, vendorId_);
      }
      if (!getPickupDateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pickupDateTime_);
      }
      if (!getDropoffDateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dropoffDateTime_);
      }
      if (!getStoreAndForwardBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, storeAndForward_);
      }
      if (rateCodeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, rateCodeId_);
      }
      if (pULocationID_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, pULocationID_);
      }
      if (dOLocationID_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, dOLocationID_);
      }
      if (passengerCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, passengerCount_);
      }
      if (tripDistance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, tripDistance_);
      }
      if (fareAmount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, fareAmount_);
      }
      if (surcharge_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, surcharge_);
      }
      if (mTATax_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, mTATax_);
      }
      if (tipAmount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, tipAmount_);
      }
      if (tollsAmount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(15, tollsAmount_);
      }
      if (improvementSurcharge_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(16, improvementSurcharge_);
      }
      if (totalAmount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(17, totalAmount_);
      }
      if (paymentTypeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(18, paymentTypeId_);
      }
      if (congestionSurcharge_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(19, congestionSurcharge_);
      }
      if (tripType_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(20, tripType_);
      }
      if (ehailFee_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(21, ehailFee_);
      }
      if (!getPartitionDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(22, partitionDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TaxiTripOuterClass.TaxiTrip)) {
        return super.equals(obj);
      }
      TaxiTripOuterClass.TaxiTrip other = (TaxiTripOuterClass.TaxiTrip) obj;

      if (!getTaxiCompany()
          .equals(other.getTaxiCompany())) return false;
      if (getVendorId()
          != other.getVendorId()) return false;
      if (!getPickupDateTime()
          .equals(other.getPickupDateTime())) return false;
      if (!getDropoffDateTime()
          .equals(other.getDropoffDateTime())) return false;
      if (!getStoreAndForward()
          .equals(other.getStoreAndForward())) return false;
      if (getRateCodeId()
          != other.getRateCodeId()) return false;
      if (getPULocationID()
          != other.getPULocationID()) return false;
      if (getDOLocationID()
          != other.getDOLocationID()) return false;
      if (getPassengerCount()
          != other.getPassengerCount()) return false;
      if (java.lang.Double.doubleToLongBits(getTripDistance())
          != java.lang.Double.doubleToLongBits(
              other.getTripDistance())) return false;
      if (java.lang.Double.doubleToLongBits(getFareAmount())
          != java.lang.Double.doubleToLongBits(
              other.getFareAmount())) return false;
      if (java.lang.Double.doubleToLongBits(getSurcharge())
          != java.lang.Double.doubleToLongBits(
              other.getSurcharge())) return false;
      if (java.lang.Double.doubleToLongBits(getMTATax())
          != java.lang.Double.doubleToLongBits(
              other.getMTATax())) return false;
      if (java.lang.Double.doubleToLongBits(getTipAmount())
          != java.lang.Double.doubleToLongBits(
              other.getTipAmount())) return false;
      if (java.lang.Double.doubleToLongBits(getTollsAmount())
          != java.lang.Double.doubleToLongBits(
              other.getTollsAmount())) return false;
      if (java.lang.Double.doubleToLongBits(getImprovementSurcharge())
          != java.lang.Double.doubleToLongBits(
              other.getImprovementSurcharge())) return false;
      if (java.lang.Double.doubleToLongBits(getTotalAmount())
          != java.lang.Double.doubleToLongBits(
              other.getTotalAmount())) return false;
      if (getPaymentTypeId()
          != other.getPaymentTypeId()) return false;
      if (java.lang.Double.doubleToLongBits(getCongestionSurcharge())
          != java.lang.Double.doubleToLongBits(
              other.getCongestionSurcharge())) return false;
      if (getTripType()
          != other.getTripType()) return false;
      if (java.lang.Double.doubleToLongBits(getEhailFee())
          != java.lang.Double.doubleToLongBits(
              other.getEhailFee())) return false;
      if (!getPartitionDate()
          .equals(other.getPartitionDate())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TAXICOMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getTaxiCompany().hashCode();
      hash = (37 * hash) + VENDOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVendorId());
      hash = (37 * hash) + PICKUP_DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getPickupDateTime().hashCode();
      hash = (37 * hash) + DROPOFF_DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getDropoffDateTime().hashCode();
      hash = (37 * hash) + STORE_AND_FORWARD_FIELD_NUMBER;
      hash = (53 * hash) + getStoreAndForward().hashCode();
      hash = (37 * hash) + RATE_CODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRateCodeId());
      hash = (37 * hash) + PULOCATIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPULocationID());
      hash = (37 * hash) + DOLOCATIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDOLocationID());
      hash = (37 * hash) + PASSENGER_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPassengerCount());
      hash = (37 * hash) + TRIP_DISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTripDistance()));
      hash = (37 * hash) + FARE_AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getFareAmount()));
      hash = (37 * hash) + SURCHARGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSurcharge()));
      hash = (37 * hash) + MTA_TAX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMTATax()));
      hash = (37 * hash) + TIP_AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTipAmount()));
      hash = (37 * hash) + TOLLS_AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTollsAmount()));
      hash = (37 * hash) + IMPROVEMENT_SURCHARGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getImprovementSurcharge()));
      hash = (37 * hash) + TOTAL_AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTotalAmount()));
      hash = (37 * hash) + PAYMENT_TYPE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPaymentTypeId());
      hash = (37 * hash) + CONGESTION_SURCHARGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCongestionSurcharge()));
      hash = (37 * hash) + TRIP_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTripType());
      hash = (37 * hash) + EHAIL_FEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getEhailFee()));
      hash = (37 * hash) + PARTITIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + getPartitionDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TaxiTripOuterClass.TaxiTrip parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaxiTripOuterClass.TaxiTrip parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaxiTripOuterClass.TaxiTrip parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaxiTripOuterClass.TaxiTrip parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaxiTripOuterClass.TaxiTrip parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaxiTripOuterClass.TaxiTrip parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaxiTripOuterClass.TaxiTrip parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TaxiTripOuterClass.TaxiTrip parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TaxiTripOuterClass.TaxiTrip parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TaxiTripOuterClass.TaxiTrip parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TaxiTripOuterClass.TaxiTrip parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TaxiTripOuterClass.TaxiTrip parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TaxiTripOuterClass.TaxiTrip prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TaxiTrip}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TaxiTrip)
        TaxiTripOuterClass.TaxiTripOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TaxiTripOuterClass.internal_static_TaxiTrip_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TaxiTripOuterClass.internal_static_TaxiTrip_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TaxiTripOuterClass.TaxiTrip.class, TaxiTripOuterClass.TaxiTrip.Builder.class);
      }

      // Construct using TaxiTripOuterClass.TaxiTrip.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        taxiCompany_ = "";

        vendorId_ = 0L;

        pickupDateTime_ = "";

        dropoffDateTime_ = "";

        storeAndForward_ = "";

        rateCodeId_ = 0L;

        pULocationID_ = 0L;

        dOLocationID_ = 0L;

        passengerCount_ = 0L;

        tripDistance_ = 0D;

        fareAmount_ = 0D;

        surcharge_ = 0D;

        mTATax_ = 0D;

        tipAmount_ = 0D;

        tollsAmount_ = 0D;

        improvementSurcharge_ = 0D;

        totalAmount_ = 0D;

        paymentTypeId_ = 0L;

        congestionSurcharge_ = 0D;

        tripType_ = 0L;

        ehailFee_ = 0D;

        partitionDate_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TaxiTripOuterClass.internal_static_TaxiTrip_descriptor;
      }

      @java.lang.Override
      public TaxiTripOuterClass.TaxiTrip getDefaultInstanceForType() {
        return TaxiTripOuterClass.TaxiTrip.getDefaultInstance();
      }

      @java.lang.Override
      public TaxiTripOuterClass.TaxiTrip build() {
        TaxiTripOuterClass.TaxiTrip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TaxiTripOuterClass.TaxiTrip buildPartial() {
        TaxiTripOuterClass.TaxiTrip result = new TaxiTripOuterClass.TaxiTrip(this);
        result.taxiCompany_ = taxiCompany_;
        result.vendorId_ = vendorId_;
        result.pickupDateTime_ = pickupDateTime_;
        result.dropoffDateTime_ = dropoffDateTime_;
        result.storeAndForward_ = storeAndForward_;
        result.rateCodeId_ = rateCodeId_;
        result.pULocationID_ = pULocationID_;
        result.dOLocationID_ = dOLocationID_;
        result.passengerCount_ = passengerCount_;
        result.tripDistance_ = tripDistance_;
        result.fareAmount_ = fareAmount_;
        result.surcharge_ = surcharge_;
        result.mTATax_ = mTATax_;
        result.tipAmount_ = tipAmount_;
        result.tollsAmount_ = tollsAmount_;
        result.improvementSurcharge_ = improvementSurcharge_;
        result.totalAmount_ = totalAmount_;
        result.paymentTypeId_ = paymentTypeId_;
        result.congestionSurcharge_ = congestionSurcharge_;
        result.tripType_ = tripType_;
        result.ehailFee_ = ehailFee_;
        result.partitionDate_ = partitionDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TaxiTripOuterClass.TaxiTrip) {
          return mergeFrom((TaxiTripOuterClass.TaxiTrip)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TaxiTripOuterClass.TaxiTrip other) {
        if (other == TaxiTripOuterClass.TaxiTrip.getDefaultInstance()) return this;
        if (!other.getTaxiCompany().isEmpty()) {
          taxiCompany_ = other.taxiCompany_;
          onChanged();
        }
        if (other.getVendorId() != 0L) {
          setVendorId(other.getVendorId());
        }
        if (!other.getPickupDateTime().isEmpty()) {
          pickupDateTime_ = other.pickupDateTime_;
          onChanged();
        }
        if (!other.getDropoffDateTime().isEmpty()) {
          dropoffDateTime_ = other.dropoffDateTime_;
          onChanged();
        }
        if (!other.getStoreAndForward().isEmpty()) {
          storeAndForward_ = other.storeAndForward_;
          onChanged();
        }
        if (other.getRateCodeId() != 0L) {
          setRateCodeId(other.getRateCodeId());
        }
        if (other.getPULocationID() != 0L) {
          setPULocationID(other.getPULocationID());
        }
        if (other.getDOLocationID() != 0L) {
          setDOLocationID(other.getDOLocationID());
        }
        if (other.getPassengerCount() != 0L) {
          setPassengerCount(other.getPassengerCount());
        }
        if (other.getTripDistance() != 0D) {
          setTripDistance(other.getTripDistance());
        }
        if (other.getFareAmount() != 0D) {
          setFareAmount(other.getFareAmount());
        }
        if (other.getSurcharge() != 0D) {
          setSurcharge(other.getSurcharge());
        }
        if (other.getMTATax() != 0D) {
          setMTATax(other.getMTATax());
        }
        if (other.getTipAmount() != 0D) {
          setTipAmount(other.getTipAmount());
        }
        if (other.getTollsAmount() != 0D) {
          setTollsAmount(other.getTollsAmount());
        }
        if (other.getImprovementSurcharge() != 0D) {
          setImprovementSurcharge(other.getImprovementSurcharge());
        }
        if (other.getTotalAmount() != 0D) {
          setTotalAmount(other.getTotalAmount());
        }
        if (other.getPaymentTypeId() != 0L) {
          setPaymentTypeId(other.getPaymentTypeId());
        }
        if (other.getCongestionSurcharge() != 0D) {
          setCongestionSurcharge(other.getCongestionSurcharge());
        }
        if (other.getTripType() != 0L) {
          setTripType(other.getTripType());
        }
        if (other.getEhailFee() != 0D) {
          setEhailFee(other.getEhailFee());
        }
        if (!other.getPartitionDate().isEmpty()) {
          partitionDate_ = other.partitionDate_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TaxiTripOuterClass.TaxiTrip parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TaxiTripOuterClass.TaxiTrip) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object taxiCompany_ = "";
      /**
       * <code>string TaxiCompany = 1;</code>
       * @return The taxiCompany.
       */
      public java.lang.String getTaxiCompany() {
        java.lang.Object ref = taxiCompany_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taxiCompany_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string TaxiCompany = 1;</code>
       * @return The bytes for taxiCompany.
       */
      public com.google.protobuf.ByteString
          getTaxiCompanyBytes() {
        java.lang.Object ref = taxiCompany_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taxiCompany_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string TaxiCompany = 1;</code>
       * @param value The taxiCompany to set.
       * @return This builder for chaining.
       */
      public Builder setTaxiCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        taxiCompany_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string TaxiCompany = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaxiCompany() {

        taxiCompany_ = getDefaultInstance().getTaxiCompany();
        onChanged();
        return this;
      }
      /**
       * <code>string TaxiCompany = 1;</code>
       * @param value The bytes for taxiCompany to set.
       * @return This builder for chaining.
       */
      public Builder setTaxiCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        taxiCompany_ = value;
        onChanged();
        return this;
      }

      private long vendorId_ ;
      /**
       * <code>int64 Vendor_Id = 2;</code>
       * @return The vendorId.
       */
      @java.lang.Override
      public long getVendorId() {
        return vendorId_;
      }
      /**
       * <code>int64 Vendor_Id = 2;</code>
       * @param value The vendorId to set.
       * @return This builder for chaining.
       */
      public Builder setVendorId(long value) {

        vendorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 Vendor_Id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVendorId() {

        vendorId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object pickupDateTime_ = "";
      /**
       * <code>string Pickup_DateTime = 3;</code>
       * @return The pickupDateTime.
       */
      public java.lang.String getPickupDateTime() {
        java.lang.Object ref = pickupDateTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pickupDateTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Pickup_DateTime = 3;</code>
       * @return The bytes for pickupDateTime.
       */
      public com.google.protobuf.ByteString
          getPickupDateTimeBytes() {
        java.lang.Object ref = pickupDateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pickupDateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Pickup_DateTime = 3;</code>
       * @param value The pickupDateTime to set.
       * @return This builder for chaining.
       */
      public Builder setPickupDateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        pickupDateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Pickup_DateTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPickupDateTime() {

        pickupDateTime_ = getDefaultInstance().getPickupDateTime();
        onChanged();
        return this;
      }
      /**
       * <code>string Pickup_DateTime = 3;</code>
       * @param value The bytes for pickupDateTime to set.
       * @return This builder for chaining.
       */
      public Builder setPickupDateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        pickupDateTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dropoffDateTime_ = "";
      /**
       * <code>string Dropoff_DateTime = 4;</code>
       * @return The dropoffDateTime.
       */
      public java.lang.String getDropoffDateTime() {
        java.lang.Object ref = dropoffDateTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dropoffDateTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Dropoff_DateTime = 4;</code>
       * @return The bytes for dropoffDateTime.
       */
      public com.google.protobuf.ByteString
          getDropoffDateTimeBytes() {
        java.lang.Object ref = dropoffDateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dropoffDateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Dropoff_DateTime = 4;</code>
       * @param value The dropoffDateTime to set.
       * @return This builder for chaining.
       */
      public Builder setDropoffDateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        dropoffDateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Dropoff_DateTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDropoffDateTime() {

        dropoffDateTime_ = getDefaultInstance().getDropoffDateTime();
        onChanged();
        return this;
      }
      /**
       * <code>string Dropoff_DateTime = 4;</code>
       * @param value The bytes for dropoffDateTime to set.
       * @return This builder for chaining.
       */
      public Builder setDropoffDateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        dropoffDateTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object storeAndForward_ = "";
      /**
       * <code>string Store_And_Forward = 5;</code>
       * @return The storeAndForward.
       */
      public java.lang.String getStoreAndForward() {
        java.lang.Object ref = storeAndForward_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          storeAndForward_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Store_And_Forward = 5;</code>
       * @return The bytes for storeAndForward.
       */
      public com.google.protobuf.ByteString
          getStoreAndForwardBytes() {
        java.lang.Object ref = storeAndForward_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          storeAndForward_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Store_And_Forward = 5;</code>
       * @param value The storeAndForward to set.
       * @return This builder for chaining.
       */
      public Builder setStoreAndForward(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        storeAndForward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Store_And_Forward = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStoreAndForward() {

        storeAndForward_ = getDefaultInstance().getStoreAndForward();
        onChanged();
        return this;
      }
      /**
       * <code>string Store_And_Forward = 5;</code>
       * @param value The bytes for storeAndForward to set.
       * @return This builder for chaining.
       */
      public Builder setStoreAndForwardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        storeAndForward_ = value;
        onChanged();
        return this;
      }

      private long rateCodeId_ ;
      /**
       * <code>int64 Rate_Code_Id = 6;</code>
       * @return The rateCodeId.
       */
      @java.lang.Override
      public long getRateCodeId() {
        return rateCodeId_;
      }
      /**
       * <code>int64 Rate_Code_Id = 6;</code>
       * @param value The rateCodeId to set.
       * @return This builder for chaining.
       */
      public Builder setRateCodeId(long value) {

        rateCodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 Rate_Code_Id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRateCodeId() {

        rateCodeId_ = 0L;
        onChanged();
        return this;
      }

      private long pULocationID_ ;
      /**
       * <code>int64 PULocationID = 7;</code>
       * @return The pULocationID.
       */
      @java.lang.Override
      public long getPULocationID() {
        return pULocationID_;
      }
      /**
       * <code>int64 PULocationID = 7;</code>
       * @param value The pULocationID to set.
       * @return This builder for chaining.
       */
      public Builder setPULocationID(long value) {

        pULocationID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 PULocationID = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPULocationID() {

        pULocationID_ = 0L;
        onChanged();
        return this;
      }

      private long dOLocationID_ ;
      /**
       * <code>int64 DOLocationID = 8;</code>
       * @return The dOLocationID.
       */
      @java.lang.Override
      public long getDOLocationID() {
        return dOLocationID_;
      }
      /**
       * <code>int64 DOLocationID = 8;</code>
       * @param value The dOLocationID to set.
       * @return This builder for chaining.
       */
      public Builder setDOLocationID(long value) {

        dOLocationID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 DOLocationID = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearDOLocationID() {

        dOLocationID_ = 0L;
        onChanged();
        return this;
      }

      private long passengerCount_ ;
      /**
       * <code>int64 Passenger_Count = 9;</code>
       * @return The passengerCount.
       */
      @java.lang.Override
      public long getPassengerCount() {
        return passengerCount_;
      }
      /**
       * <code>int64 Passenger_Count = 9;</code>
       * @param value The passengerCount to set.
       * @return This builder for chaining.
       */
      public Builder setPassengerCount(long value) {

        passengerCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 Passenger_Count = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassengerCount() {

        passengerCount_ = 0L;
        onChanged();
        return this;
      }

      private double tripDistance_ ;
      /**
       * <code>double Trip_Distance = 10;</code>
       * @return The tripDistance.
       */
      @java.lang.Override
      public double getTripDistance() {
        return tripDistance_;
      }
      /**
       * <code>double Trip_Distance = 10;</code>
       * @param value The tripDistance to set.
       * @return This builder for chaining.
       */
      public Builder setTripDistance(double value) {

        tripDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Trip_Distance = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearTripDistance() {

        tripDistance_ = 0D;
        onChanged();
        return this;
      }

      private double fareAmount_ ;
      /**
       * <code>double Fare_Amount = 11;</code>
       * @return The fareAmount.
       */
      @java.lang.Override
      public double getFareAmount() {
        return fareAmount_;
      }
      /**
       * <code>double Fare_Amount = 11;</code>
       * @param value The fareAmount to set.
       * @return This builder for chaining.
       */
      public Builder setFareAmount(double value) {

        fareAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Fare_Amount = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearFareAmount() {

        fareAmount_ = 0D;
        onChanged();
        return this;
      }

      private double surcharge_ ;
      /**
       * <code>double Surcharge = 12;</code>
       * @return The surcharge.
       */
      @java.lang.Override
      public double getSurcharge() {
        return surcharge_;
      }
      /**
       * <code>double Surcharge = 12;</code>
       * @param value The surcharge to set.
       * @return This builder for chaining.
       */
      public Builder setSurcharge(double value) {

        surcharge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Surcharge = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearSurcharge() {

        surcharge_ = 0D;
        onChanged();
        return this;
      }

      private double mTATax_ ;
      /**
       * <code>double MTA_Tax = 13;</code>
       * @return The mTATax.
       */
      @java.lang.Override
      public double getMTATax() {
        return mTATax_;
      }
      /**
       * <code>double MTA_Tax = 13;</code>
       * @param value The mTATax to set.
       * @return This builder for chaining.
       */
      public Builder setMTATax(double value) {

        mTATax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double MTA_Tax = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearMTATax() {

        mTATax_ = 0D;
        onChanged();
        return this;
      }

      private double tipAmount_ ;
      /**
       * <code>double Tip_Amount = 14;</code>
       * @return The tipAmount.
       */
      @java.lang.Override
      public double getTipAmount() {
        return tipAmount_;
      }
      /**
       * <code>double Tip_Amount = 14;</code>
       * @param value The tipAmount to set.
       * @return This builder for chaining.
       */
      public Builder setTipAmount(double value) {

        tipAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Tip_Amount = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearTipAmount() {

        tipAmount_ = 0D;
        onChanged();
        return this;
      }

      private double tollsAmount_ ;
      /**
       * <code>double Tolls_Amount = 15;</code>
       * @return The tollsAmount.
       */
      @java.lang.Override
      public double getTollsAmount() {
        return tollsAmount_;
      }
      /**
       * <code>double Tolls_Amount = 15;</code>
       * @param value The tollsAmount to set.
       * @return This builder for chaining.
       */
      public Builder setTollsAmount(double value) {

        tollsAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Tolls_Amount = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearTollsAmount() {

        tollsAmount_ = 0D;
        onChanged();
        return this;
      }

      private double improvementSurcharge_ ;
      /**
       * <code>double Improvement_Surcharge = 16;</code>
       * @return The improvementSurcharge.
       */
      @java.lang.Override
      public double getImprovementSurcharge() {
        return improvementSurcharge_;
      }
      /**
       * <code>double Improvement_Surcharge = 16;</code>
       * @param value The improvementSurcharge to set.
       * @return This builder for chaining.
       */
      public Builder setImprovementSurcharge(double value) {

        improvementSurcharge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Improvement_Surcharge = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearImprovementSurcharge() {

        improvementSurcharge_ = 0D;
        onChanged();
        return this;
      }

      private double totalAmount_ ;
      /**
       * <code>double Total_Amount = 17;</code>
       * @return The totalAmount.
       */
      @java.lang.Override
      public double getTotalAmount() {
        return totalAmount_;
      }
      /**
       * <code>double Total_Amount = 17;</code>
       * @param value The totalAmount to set.
       * @return This builder for chaining.
       */
      public Builder setTotalAmount(double value) {

        totalAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Total_Amount = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalAmount() {

        totalAmount_ = 0D;
        onChanged();
        return this;
      }

      private long paymentTypeId_ ;
      /**
       * <code>int64 Payment_Type_Id = 18;</code>
       * @return The paymentTypeId.
       */
      @java.lang.Override
      public long getPaymentTypeId() {
        return paymentTypeId_;
      }
      /**
       * <code>int64 Payment_Type_Id = 18;</code>
       * @param value The paymentTypeId to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentTypeId(long value) {

        paymentTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 Payment_Type_Id = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearPaymentTypeId() {

        paymentTypeId_ = 0L;
        onChanged();
        return this;
      }

      private double congestionSurcharge_ ;
      /**
       * <code>double Congestion_Surcharge = 19;</code>
       * @return The congestionSurcharge.
       */
      @java.lang.Override
      public double getCongestionSurcharge() {
        return congestionSurcharge_;
      }
      /**
       * <code>double Congestion_Surcharge = 19;</code>
       * @param value The congestionSurcharge to set.
       * @return This builder for chaining.
       */
      public Builder setCongestionSurcharge(double value) {

        congestionSurcharge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Congestion_Surcharge = 19;</code>
       * @return This builder for chaining.
       */
      public Builder clearCongestionSurcharge() {

        congestionSurcharge_ = 0D;
        onChanged();
        return this;
      }

      private long tripType_ ;
      /**
       * <code>int64 Trip_Type = 20;</code>
       * @return The tripType.
       */
      @java.lang.Override
      public long getTripType() {
        return tripType_;
      }
      /**
       * <code>int64 Trip_Type = 20;</code>
       * @param value The tripType to set.
       * @return This builder for chaining.
       */
      public Builder setTripType(long value) {

        tripType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 Trip_Type = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearTripType() {

        tripType_ = 0L;
        onChanged();
        return this;
      }

      private double ehailFee_ ;
      /**
       * <code>double Ehail_Fee = 21;</code>
       * @return The ehailFee.
       */
      @java.lang.Override
      public double getEhailFee() {
        return ehailFee_;
      }
      /**
       * <code>double Ehail_Fee = 21;</code>
       * @param value The ehailFee to set.
       * @return This builder for chaining.
       */
      public Builder setEhailFee(double value) {

        ehailFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double Ehail_Fee = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearEhailFee() {

        ehailFee_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object partitionDate_ = "";
      /**
       * <code>string PartitionDate = 22;</code>
       * @return The partitionDate.
       */
      public java.lang.String getPartitionDate() {
        java.lang.Object ref = partitionDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          partitionDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string PartitionDate = 22;</code>
       * @return The bytes for partitionDate.
       */
      public com.google.protobuf.ByteString
          getPartitionDateBytes() {
        java.lang.Object ref = partitionDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partitionDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string PartitionDate = 22;</code>
       * @param value The partitionDate to set.
       * @return This builder for chaining.
       */
      public Builder setPartitionDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        partitionDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string PartitionDate = 22;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartitionDate() {

        partitionDate_ = getDefaultInstance().getPartitionDate();
        onChanged();
        return this;
      }
      /**
       * <code>string PartitionDate = 22;</code>
       * @param value The bytes for partitionDate to set.
       * @return This builder for chaining.
       */
      public Builder setPartitionDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        partitionDate_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TaxiTrip)
    }

    // @@protoc_insertion_point(class_scope:TaxiTrip)
    private static final TaxiTripOuterClass.TaxiTrip DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TaxiTripOuterClass.TaxiTrip();
    }

    public static TaxiTripOuterClass.TaxiTrip getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaxiTrip>
        PARSER = new com.google.protobuf.AbstractParser<TaxiTrip>() {
      @java.lang.Override
      public TaxiTrip parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaxiTrip(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaxiTrip> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaxiTrip> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TaxiTripOuterClass.TaxiTrip getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TaxiTrip_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TaxiTrip_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TaxiTrip.proto\"\376\003\n\010TaxiTrip\022\023\n\013TaxiCom" +
      "pany\030\001 \001(\t\022\021\n\tVendor_Id\030\002 \001(\003\022\027\n\017Pickup_" +
      "DateTime\030\003 \001(\t\022\030\n\020Dropoff_DateTime\030\004 \001(\t" +
      "\022\031\n\021Store_And_Forward\030\005 \001(\t\022\024\n\014Rate_Code" +
      "_Id\030\006 \001(\003\022\024\n\014PULocationID\030\007 \001(\003\022\024\n\014DOLoc" +
      "ationID\030\010 \001(\003\022\027\n\017Passenger_Count\030\t \001(\003\022\025" +
      "\n\rTrip_Distance\030\n \001(\001\022\023\n\013Fare_Amount\030\013 \001" +
      "(\001\022\021\n\tSurcharge\030\014 \001(\001\022\017\n\007MTA_Tax\030\r \001(\001\022\022" +
      "\n\nTip_Amount\030\016 \001(\001\022\024\n\014Tolls_Amount\030\017 \001(\001" +
      "\022\035\n\025Improvement_Surcharge\030\020 \001(\001\022\024\n\014Total" +
      "_Amount\030\021 \001(\001\022\027\n\017Payment_Type_Id\030\022 \001(\003\022\034" +
      "\n\024Congestion_Surcharge\030\023 \001(\001\022\021\n\tTrip_Typ" +
      "e\030\024 \001(\003\022\021\n\tEhail_Fee\030\025 \001(\001\022\025\n\rPartitionD" +
      "ate\030\026 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TaxiTrip_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TaxiTrip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TaxiTrip_descriptor,
        new java.lang.String[] { "TaxiCompany", "VendorId", "PickupDateTime", "DropoffDateTime", "StoreAndForward", "RateCodeId", "PULocationID", "DOLocationID", "PassengerCount", "TripDistance", "FareAmount", "Surcharge", "MTATax", "TipAmount", "TollsAmount", "ImprovementSurcharge", "TotalAmount", "PaymentTypeId", "CongestionSurcharge", "TripType", "EhailFee", "PartitionDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
